local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#c9c8db", bg = "#191724"},
TSBoolean = {link = "Boolean"},
TSCharacter = {link = "Character"},
CmpItemAbbr = {fg = "#908caa"},
CmpItemAbbrDeprecated = {fg = "#908caa", strikethrough = true},
CmpItemAbbrMatch = {fg = "#c9c8db", bold = true},
CmpItemAbbrMatchFuzzy = {fg = "#c9c8db", bold = true},
CmpItemKind = {fg = "#31748f"},
CmpItemKindClass = {fg = "#9ccfd8"},
CmpItemKindFunction = {fg = "#31748f"},
CmpItemKindInterface = {fg = "#9ccfd8"},
CmpItemKindMethod = {fg = "#31748f"},
CmpItemKindSnippet = {fg = "#31748f"},
CmpItemKindVariable = {fg = "#8ac6f2"},
ColorColumn = {bg = "#26233a"},
Comment = {fg = "#6e6a86"},
TSComment = {link = "Comment"},
Conceal = {bg = "NONE"},
TSConditional = {link = "Conditional"},
Constant = {fg = "#f3cc95"},
Boolean = {link = "Constant"},
Character = {link = "Constant"},
Cursor = {fg = "#c9c8db", bg = "#31748f"},
CursorColumn = {bg = "#21202e"},
CursorLine = {bg = "#21202e"},
MiniFilesCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#c9c8db"},
DefinitionCount = {fg = "#ebbcba"},
DefinitionIcon = {fg = "#ebbcba"},
DefinitionPreviewTitle = {fg = "#ebbcba", bold = true},
Delimiter = {fg = "#908caa"},
DiagnosticError = {fg = "#d66B7f"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
MiniFilesBorderModified = {link = "DiagnosticFloatingWarn"},
DiagnosticHint = {fg = "#c4a7e7"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#9ccfd8"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticUnderlineError = {sp = "#d66B7f", underline = true},
DiagnosticUnderlineHint = {sp = "#c4a7e7", underline = true},
DiagnosticUnderlineInfo = {sp = "#9ccfd8", underline = true},
DiagnosticUnderlineWarn = {sp = "#f3cc95", underline = true},
DiagnosticWarn = {fg = "#f3cc95"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#9ccfd8", blend = 50},
DiffChange = {bg = "#26233a"},
DiffDelete = {bg = "#d66B7f", blend = 50},
DiffText = {bg = "#ebbcba", blend = 50},
Directory = {fg = "#9ccfd8"},
MiniFilesDirectory = {link = "Directory"},
Error = {fg = "#d66B7f"},
ErrorMsg = {fg = "#d66B7f", bold = true},
FoldColumn = {fg = "#6e6a86"},
Folded = {fg = "#c9c8db", bg = "#25232e"},
Function = {fg = "#8ac6f2"},
TSFunction = {link = "Function"},
Identifier = {fg = "#c9c8db"},
TSParameter = {link = "Identifier"},
Ignore = {fg = "bg"},
EndOfBuffer = {link = "Ignore"},
IncSearch = {fg = "#d66B7f", bg = "#524f67", bold = true, undercurl = true},
CurSearch = {link = "IncSearch"},
WildMenu = {link = "IncSearch"},
IndentBlanklineChar = {fg = "#6e6a86"},
Keyword = {fg = "#31748f"},
LineNr = {fg = "#6e6a86"},
LspCodeLens = {fg = "#908caa"},
LspCodeLensSeparator = {fg = "#524f67"},
LspFloatWinBorder = {fg = "#403d52"},
LspFloatWinNormal = {bg = "#191724"},
LspReferenceRead = {bg = "#403d52"},
LspReferenceText = {bg = "#403d52"},
LspReferenceWrite = {bg = "#403d52"},
LspSagaAutoPreview = {fg = "#908caa"},
LspSagaCodeActionBorder = {fg = "#403d52"},
LspSagaCodeActionTruncateLine = {link = "LspSagaCodeActionBorder"},
LspSagaCodeActionContent = {fg = "#9ccfd8"},
LspSagaCodeActionTitle = {fg = "#f3cc95", bold = true},
LspSagaDefPreviewBorder = {fg = "#403d52"},
LspSagaDiagnosticBorder = {fg = "#403d52"},
LspSagaDiagnosticTruncateLine = {link = "LspSagaDiagnosticBorder"},
LspSagaDiagnosticHeader = {fg = "#f3cc95", bold = true},
LspSagaFinderSelection = {fg = "#f3cc95"},
LspSagaHoverBorder = {fg = "#403d52"},
LspSagaDocTruncateLine = {link = "LspSagaHoverBorder"},
LspSagaLspFinderBorder = {fg = "#403d52"},
LspSagaRenameBorder = {fg = "#31748f"},
LspSagaRenamePromptPrefix = {fg = "#d66B7f"},
LspSagaSignatureHelpBorder = {fg = "#31748f"},
LspSagaShTruncateLine = {link = "LspSagaSignatureHelpBorder"},
LspSignatureActiveParameter = {bg = "#26233a"},
MatchParen = {fg = "#c9c8db", bg = "#403d52"},
MiniFilesBorder = {fg = "#403d52", bg = "#25232e"},
MiniFilesFile = {fg = "#c9c8db"},
MiniFilesTitle = {fg = "#9ccfd8", bg = "#25232e", bold = true},
MiniFilesTitleFocused = {fg = "#ebbcba", bg = "#25232e", bold = true},
ModeMsg = {fg = "#908caa"},
MoreMsg = {fg = "#c4a7e7"},
NonText = {fg = "#6e6a86"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#c9c8db", bg = "#25232e"},
MiniFilesNormal = {link = "NormalFloat"},
NormalNC = {fg = "#c9c8db", bg = "#191724"},
Number = {fg = "#c9c8db"},
Float = {link = "Number"},
TSNumber = {link = "Number"},
Operator = {fg = "#908caa"},
Pmenu = {fg = "#908caa", bg = "#25232e"},
PmenuSbar = {bg = "#21202e"},
PmenuSel = {fg = "#c9c8db", bg = "#403d52"},
PmenuThumb = {bg = "#403d52"},
PreProc = {fg = "#c4a7e7"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Question = {fg = "#f3cc95"},
ReferencesCount = {fg = "#ebbcba"},
ReferencesIcon = {fg = "#ebbcba"},
SagaShadow = {bg = "#26233a"},
Search = {fg = "#ebbcba", bg = "#524f67", undercurl = true},
QuickFixLine = {link = "Search"},
Substitute = {link = "Search"},
SignColumn = {fg = "#c9c8db"},
Special = {fg = "#ebbcba"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
SpecialKey = {fg = "#9ccfd8"},
SpellBad = {sp = "#d66B7f", undercurl = true},
SpellCap = {sp = "#908caa", undercurl = true},
SpellLocal = {sp = "#908caa", undercurl = true},
SpellRare = {sp = "#908caa", undercurl = true},
Statement = {fg = "#31748f"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#908caa", bg = "#25232e"},
MsgSeparator = {link = "StatusLine"},
StatusLineTerm = {link = "StatusLine"},
StatusLineNC = {fg = "#6e6a86", bg = "#191724"},
StatusLineTermNC = {link = "StatusLineNC"},
String = {fg = "#c9c8db"},
TSString = {link = "String"},
TSConstBuiltin = {fg = "#d66B7f"},
TSConstant = {fg = "#9ccfd8"},
TSConstructor = {fg = "#9ccfd8"},
TSEmphasis = {italic = true},
TSField = {fg = "#9ccfd8"},
TSFuncBuiltin = {fg = "#d66B7f"},
TSKeyword = {fg = "#31748f"},
TSKeywordOperator = {fg = "#908caa"},
TSLabel = {fg = "#9ccfd8"},
TSOperator = {fg = "#908caa"},
TSProperty = {fg = "#c4a7e7"},
TSPunctBracket = {fg = "#6e6a86"},
TSPunctDelimiter = {fg = "#6e6a86"},
TSPunctSpecial = {fg = "#6e6a86"},
TSStringSpecial = {link = "TSString"},
TSStringEscape = {fg = "#31748f"},
TSStrong = {bold = true},
TSTag = {fg = "#9ccfd8"},
TSTagDelimiter = {fg = "#908caa"},
TSText = {fg = "#c9c8db"},
TSTitle = {fg = "#c4a7e7", bold = true},
TSUnderline = {underline = true},
TSVariableBuiltin = {fg = "#d66B7f"},
TabLine = {fg = "#908caa", bg = "#25232e"},
TabLineFill = {bg = "#25232e"},
TabLineSel = {fg = "#c9c8db", bg = "#26233a"},
TargetWord = {fg = "#c4a7e7"},
TelescopeBorder = {fg = "#403d52", bg = "#25232e"},
TelescopeMatching = {fg = "#ebbcba"},
TelescopeNormal = {fg = "#908caa", bg = "#25232e"},
TelescopePreviewNormal = {fg = "#c9c8db", bg = "#25232e"},
TelescopePromptNormal = {fg = "#c9c8db", bg = "#25232e"},
TelescopePromptPrefix = {fg = "#908caa"},
TelescopeSelection = {fg = "#c9c8db", bg = "#26233a"},
TelescopeSelectionCaret = {fg = "#ebbcba", bg = "#26233a"},
TelescopeTitle = {fg = "#908caa"},
TermCursor = {reverse = true},
Title = {fg = "#c9c8db"},
Todo = {fg = "#c4a7e7"},
TSWarning = {link = "Todo"},
Type = {fg = "#9ccfd8"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
TSEnvironmentName = {link = "Type"},
TSType = {link = "Type"},
Typedef = {link = "Type"},
Underlined = {fg = "#c4a7e7", underline = true},
TSURI = {link = "Underlined"},
VertSplit = {fg = "#403d52"},
WinSeparator = {link = "VertSplit"},
Visual = {bg = "#403d52"},
WarningMsg = {fg = "#d66B7f"},
TSDanger = {link = "WarningMsg"},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd('highlight clear')
vim.cmd('set t_Co=256')
vim.g.colors_name = 'calorie'

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
